# Generated by Django 5.0.3 on 2025-03-11 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
