# Generated by Django 5.0.3 on 2025-03-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_id_alter_post_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='temp_id',
            new_name='id',
        ),
    ]
