# Generated by Django 5.0.3 on 2025-03-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
    ]
