# Generated by Django 5.0.3 on 2025-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
