# Generated by Django 5.0.3 on 2025-03-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_display_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='display_description',
            field=models.CharField(max_length=150),
        ),
    ]
