# Generated by Django 5.0.3 on 2025-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_options_alter_post_display_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin_post',
            field=models.BooleanField(default=False),
        ),
    ]
