# Generated by Django 5.0.3 on 2026-07-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pin_post', 'date_created']},
        ),
    ]
